### ISSUE TITLE
Vertical alignment of icons, when "Lines of text" is greater than "1", should be top

### ISSUE THREAD

**Issue by ghost** [ligi/FAST#35]
How to produce it:
- change "Lines of text" option in FAST to 2 or 3 (default is 1 - one line of text);
- rebuild cache;
- scroll to bottom of app list and then scroll up.

What shoud happen:
Icons in app list should be vertically aligned to top.

What happens instead:
Icons in app list will be vertically aligned to bottom instead of top.

Here is the sshot:
http://i.imgur.com/SEMVH9q.png
Notice "K-9 Mail", "Dev Tools" and "Droid Life" icons.

**Comment by SebiderSushi** [comment]
Found this answer to the exact same problem:
https://stackoverflow.com/questions/4106017/gridview-sometimes-rows-are-top-aligned-sometimes-theyre-bottom-aligned

One minor issue I can think of:
When specifying
`labelView.setMinLines(maxLines);`
istead of
`labelView.setMaxLines(maxLines);`
there is a bit loss of screen space because in the first case there might be rows where all labes use less lines then the maximum number of lines and are hence thinner.
