### ISSUE TITLE
Failing to save app data on reboot might be due to a bug in the packageChangedListener

### ISSUE THREAD

**Issue by ShadowKyogre** [ligi/FAST#74]
Source of the original bug: https://play.google.com/store/apps/details?id=org.ligi.fast&reviewId=Z3A6QU9xcFRPRXQyS0FsRm5sRW5FN1NrVGN6ZHNmNm42aUYtOHlSMHlPdUhIcjVQQjRFbzVicVFaQmd0cG0xeW9ZZC1BRnRTcW1Lcjd1aGIzbkNacDdGZHc

Although this is with a custom build where I'm trying to implement the pin feature in a stable manner, I am able to easily reproduce the bug here just by installing/removing a package.

![2015-02-04-17 27 21](https://cloud.githubusercontent.com/assets/673620/6053444/30d11bde-ac94-11e4-88a9-e83d4b8c2ef7.png)
This screenshot was after I installed a random application on a test phone I had laying around after setting up some breakpoints in Android studio.

---

![2015-02-04-17 29 04](https://cloud.githubusercontent.com/assets/673620/6053452/4c9fa0d8-ac94-11e4-94ba-84972b7b5437.png)
This screenshot was after I went ahead and pinned the app before exiting it normally, using the same breakpoints.

---

![2015-02-04-17 31 32](https://cloud.githubusercontent.com/assets/673620/6053474/b12b57cc-ac94-11e4-88bc-4ca4cf5eba65.png)
This screenshot was after I uninstalled a random application on a test phone I had laying around, using the same breakpoints.

**Comment by ligi** [comment]
thanks for the Investigation! But I do not yet see what you see on these screenshots ;-) Just different cases saving the app-info list - can you give some more insight?

**Comment by ShadowKyogre** [comment]
@ligi: The line to keep an eye out in the screenies is the pinMode (which I set up in a similar way to callCount). In both the package uninstall and install cases, Camera's pinMode isn't retained during package install and uninstall. Further investigation showed that for some reason, the oldInfo in the oldAppList in the BaseAppGatherAsyncTask didn't retain neither the custom field nor the launch count (<- this was during later tests).

The way I was able to see this was by putting a breakpoint on line 54 of BaseAppGatherAsyncTask for a certain package that I knew had a different pin mode or launch count. When you try this after uninstalling and installing packages, you should be able to see the oldInfo and the actAppInfo in the variables pane for comparison.

**Comment by ligi** [comment]
ah I ignored pinMode as it is not in my version - will have a closer look at the merger

**Comment by SebiderSushi** [comment]
I've found and fixed (674298d5c174103a6d6070fd7223b0689694db5b) a bug where app data got reset every time an app was installed or removed while FAST wasn't running, i.e. the list got updated via
`new BackgroundGatherAsyncTask(context, appInfoListStore.load()).execute();`
while `onPackageChange()` was set to
`appInfoListStore.save(appInfoList);`

As you can see the `BackgroundGatherAsyncTask` was simply dropping the old info by iterating through `appInfoList` instead of `oldAppList`. Whenever fast is running `onPackageChange()` is set to effectively use `DynamicAppInfoList.update()` and hence merges the old info anyway.

This has somehow been introduced in ff33ab4131b4c6864bb8c44fc9fdabe0c8783fee (see line comment) over three years ago...
